
import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { generateSpatialAnalysis, SpatialAnalysisResult } from '../services/geminiService';
import SpatialAnalysisInputForm from './SpatialAnalysisInputForm';
import { motion } from 'motion/react';
import GeneratorShell from './GeneratorShell';
import jsPDF from 'jspdf';
import { FileText, RefreshCw, BarChart3, Map as MapIcon, Eye } from 'lucide-react';
import { MapContainer, TileLayer, ImageOverlay, Rectangle, CircleMarker, Popup } from 'react-leaflet';
import { LatLngBounds } from 'leaflet';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';

// Fix for default marker icons in Leaflet
delete (L.Icon.Default.prototype as { _getIconUrl?: unknown })._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon-2x.png',
  iconUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon.png',
  shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png',
});

interface GeneratorProps {
  onUpgrade: () => void;
}

const SpatialAnalysisGenerator: React.FC<GeneratorProps> = ({ onUpgrade }) => {
  const { user, profile, loading, refreshProfile, signInWithGoogle } = useAuth();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<SpatialAnalysisResult | null>(null);
  const [projectInfo, setProjectInfo] = useState({ cityName: '', analysisTopic: '' });
  const [capturedBounds, setCapturedBounds] = useState<LatLngBounds | undefined>(undefined);
  const [isInteractive, setIsInteractive] = useState(false);

  const handleGenerate = async (cityName: string, analysisTopic: string, file: File, bounds?: LatLngBounds) => {
    // High-quality spatial analysis requires a paid API key for gemini-3.1-flash-image-preview
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const hasKey = await (window as any).aistudio?.hasSelectedApiKey();
      if (!hasKey) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await (window as any).aistudio?.openSelectKey();
        // Proceeding as per baseline: "you MUST assume the key selection was successful after triggering openSelectKey() and proceed to the app."
      }
    } catch (err) {
      console.warn("API Key selection check failed, proceeding with default:", err);
    }

    setIsLoading(true);
    setError(null);
    setResult(null);
    setProjectInfo({ cityName, analysisTopic });
    setCapturedBounds(bounds);
    setIsInteractive(false);

    try {
      // If bounds weren't provided (e.g. file upload), try to geocode the city
      if (!bounds) {
        try {
          const geoResponse = await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(cityName)}&limit=1`);
          const geoData = await geoResponse.json();
          if (geoData && geoData.length > 0) {
            const bbox = geoData[0].boundingbox; // [south, north, west, east]
            setCapturedBounds(new L.LatLngBounds([parseFloat(bbox[0]), parseFloat(bbox[2])], [parseFloat(bbox[1]), parseFloat(bbox[3])]));
          }
        } catch (geoErr) {
          console.warn("Geocoding failed, interactive map might not center correctly:", geoErr);
        }
      }

      const analysisResult = await generateSpatialAnalysis({ cityName, analysisTopic }, file);
      setResult(analysisResult);
      await refreshProfile();
    } catch (err: unknown) {
      console.error('Spatial Analysis Error:', err);
      setError(err instanceof Error ? err.message : 'An unexpected error occurred during spatial analysis.');
    } finally {
      setIsLoading(false);
    }
  };

  const generatePDF = () => {
    if (!result) return;
    
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - 2 * margin;

    // PAGE 1 - COVER
    doc.setFillColor(15, 23, 42); // Deep blue theme
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('TANNMYAA Intelligence', margin, 25);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text(`Spatial Analysis Report`, pageWidth / 2, 80, { align: 'center' });
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text(`${projectInfo.cityName}`, pageWidth / 2, 95, { align: 'center' });
    doc.setFontSize(14);
    doc.text(`${projectInfo.analysisTopic}`, pageWidth / 2, 105, { align: 'center' });
    
    doc.setDrawColor(15, 23, 42);
    doc.setLineWidth(0.5);
    doc.line(margin, 115, pageWidth - margin, 115);
    
    doc.setFontSize(10);
    doc.text(`Generated by TANNMYAA Spatial Engine V5`, pageWidth / 2, 125, { align: 'center' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, 132, { align: 'center' });
    doc.text(`© TANNMYAA ${new Date().getFullYear()}`, pageWidth / 2, 100, { align: 'center' });

    // Add map image
    try {
      const isPng = result.imageUrl.includes('image/png');
      const format = isPng ? 'PNG' : 'JPEG';
      doc.addImage(result.imageUrl, format, margin, 120, contentWidth, (contentWidth * 9) / 16);
    } catch (e) {
      console.error("Could not add image to PDF", e);
    }

    doc.save(`Spatial_Analysis_Map_${projectInfo.cityName.replace(/\s+/g, '_')}.pdf`);
  };

  const handleUpdatePoint = (idx: number, updates: Partial<typeof result.interactiveData.points[0]>) => {
    if (!result || !result.interactiveData) return;
    const newPoints = [...result.interactiveData.points];
    newPoints[idx] = { ...newPoints[idx], ...updates };
    setResult({
      ...result,
      interactiveData: {
        ...result.interactiveData,
        points: newPoints
      }
    });
  };

  const handleUpdateZone = (idx: number, updates: Partial<typeof result.interactiveData.zones[0]>) => {
    if (!result || !result.interactiveData || !result.interactiveData.zones) return;
    const newZones = [...result.interactiveData.zones];
    newZones[idx] = { ...newZones[idx], ...updates };
    setResult({
      ...result,
      interactiveData: {
        ...result.interactiveData,
        zones: newZones
      }
    });
  };

  const renderInputForm = () => (
    <motion.div
      key="form"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
    >
      <SpatialAnalysisInputForm 
        onSubmit={handleGenerate}
        isLoading={isLoading}
        credits={profile?.credits || 0}
        userEmail={user?.email || null}
        onLogin={signInWithGoogle}
      />
    </motion.div>
  );

  const renderResult = (res: SpatialAnalysisResult) => (
    <motion.div
      key="result"
      initial={{ opacity: 0, scale: 0.98 }}
      animate={{ opacity: 1, scale: 1 }}
      className="space-y-10 animate-fade-in max-w-7xl mx-auto"
    >
      {/* Dark Theme Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 px-2 bg-gray-900/70 backdrop-blur-xl border border-gray-700/80 rounded-[32px] p-8 md:p-10 shadow-2xl">
        <div className="space-y-1">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 bg-white text-gray-900 flex items-center justify-center rounded-xl font-black text-2xl shadow-lg">T</div>
            <div className="flex flex-col">
              <span className="text-white font-bold text-sm tracking-[0.3em] uppercase">TANNMYAA</span>
              <span className="text-blue-400 font-bold text-[10px] uppercase tracking-[0.2em]">Intelligence</span>
            </div>
          </div>
          <h2 className="text-4xl font-bold text-white tracking-tight">
            {projectInfo.cityName}
          </h2>
          <p className="text-gray-400 text-lg font-medium">
            {projectInfo.analysisTopic}
          </p>
        </div>
        <div className="flex flex-wrap gap-3">
          <button 
            onClick={() => setIsInteractive(!isInteractive)}
            className={`flex items-center gap-2 text-sm px-6 py-3 rounded-full font-semibold transition-all duration-300 shadow-lg ${isInteractive ? 'bg-blue-600 text-white shadow-blue-500/20' : 'bg-gray-800 text-gray-200 hover:bg-gray-700 border border-gray-700'}`}
          >
            {isInteractive ? <Eye size={16} /> : <MapIcon size={16} />}
            {isInteractive ? 'Static View' : 'Interactive Map'}
          </button>
          <button 
            onClick={generatePDF}
            className="flex items-center gap-2 text-sm px-6 py-3 rounded-full font-semibold bg-gray-800 text-gray-200 hover:bg-gray-700 border border-gray-700 shadow-lg transition-all duration-300"
          >
            <FileText size={16} />
            Export Map PDF
          </button>
          <button 
            onClick={() => setResult(null)}
            className="flex items-center gap-2 text-sm px-6 py-3 rounded-full font-semibold bg-white/5 text-gray-400 hover:bg-white/10 border border-white/5 transition-all duration-300"
          >
            <RefreshCw size={16} />
            Reset
          </button>
        </div>
      </div>

      <div className="max-w-5xl mx-auto">
        {/* Main Map Area */}
        <div className="bg-gray-900/70 backdrop-blur-xl border border-gray-700/80 rounded-[32px] overflow-hidden relative group aspect-[9/16] md:aspect-[16/10] flex flex-col shadow-2xl">
          <div className="absolute top-6 left-6 z-[1000] flex flex-col gap-2">
            <div className="bg-black/60 backdrop-blur-md border border-white/10 px-4 py-2 rounded-2xl text-[11px] text-white font-bold flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-green-500" />
              {isInteractive ? 'INTERACTIVE_GEOSPATIAL' : 'ANALYTICAL_STATIC'}
            </div>
            <div className="bg-blue-600/20 backdrop-blur-md border border-blue-500/20 px-4 py-2 rounded-2xl text-[10px] text-blue-300 font-bold flex items-center gap-2">
              <BarChart3 size={12} />
              PROFESSIONAL_CARTOGRAPHIC_STANDARD
            </div>
          </div>
          
          <div className="flex-1 relative bg-black/40">
            {isInteractive && capturedBounds ? (
              <MapContainer 
                bounds={capturedBounds} 
                style={{ height: '100%', width: '100%' }}
                zoomControl={false}
              >
                <TileLayer
                  attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
                  url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"
                />
                <ImageOverlay
                  url={res.imageUrl}
                  bounds={capturedBounds}
                  opacity={0.8}
                />
                
                {/* Interactive Deep Analysis Layer */}
                {res.interactiveData && (
                  <>
                    {res.interactiveData.zones?.map((zone, idx) => (
                      <Rectangle
                        key={`zone-${idx}`}
                        bounds={zone.bounds}
                        pathOptions={{ 
                          color: zone.color || '#3b82f6', 
                          fillColor: zone.color || '#3b82f6',
                          fillOpacity: 0.2,
                          weight: 2,
                          dashArray: '5, 5'
                        }}
                      >
                        <Popup className="custom-leaflet-popup">
                            <div className="p-1 min-w-[180px]">
                              <input 
                                className="font-bold text-blue-400 text-sm mb-1 bg-transparent border-none focus:ring-1 focus:ring-blue-500 rounded w-full"
                                value={zone.title}
                                onChange={(e) => handleUpdateZone(idx, { title: e.target.value })}
                              />
                              <textarea 
                                className="text-[11px] text-gray-200 leading-relaxed bg-transparent border-none focus:ring-1 focus:ring-blue-500 rounded w-full resize-none"
                                value={zone.description}
                                rows={3}
                                onChange={(e) => handleUpdateZone(idx, { description: e.target.value })}
                              />
                            </div>
                        </Popup>
                      </Rectangle>
                    ))}
                    
                    {res.interactiveData.points.map((point, idx) => (
                      <CircleMarker
                        key={`point-${idx}`}
                        center={[point.lat, point.lng]}
                        radius={8}
                        pathOptions={{
                          fillColor: point.type === 'warning' ? '#ef4444' : 
                                     point.type === 'opportunity' ? '#10b981' : 
                                     point.type === 'insight' ? '#3b82f6' : '#f59e0b',
                          color: '#fff',
                          weight: 2,
                          fillOpacity: 0.9
                        }}
                      >
                        <Popup className="custom-leaflet-popup">
                            <div className="p-1 min-w-[200px]">
                              <div className="flex items-center gap-2 mb-2">
                                <div className={`w-2 h-2 rounded-full ${
                                  point.type === 'warning' ? 'bg-red-500' : 
                                  point.type === 'opportunity' ? 'bg-green-500' : 
                                  point.type === 'insight' ? 'bg-blue-500' : 'bg-yellow-500'
                                }`} />
                                <input 
                                  className="font-bold text-white text-sm bg-transparent border-none focus:ring-1 focus:ring-blue-500 rounded w-full"
                                  value={point.title}
                                  onChange={(e) => handleUpdatePoint(idx, { title: e.target.value })}
                                />
                              </div>
                              <textarea 
                                className="text-[11px] text-gray-300 leading-relaxed mb-2 bg-transparent border-none focus:ring-1 focus:ring-blue-500 rounded w-full resize-none"
                                value={point.description}
                                rows={3}
                                onChange={(e) => handleUpdatePoint(idx, { description: e.target.value })}
                              />
                              <div className="pt-2 border-t border-gray-800 flex justify-between items-center">
                                <select 
                                  className="text-[9px] uppercase font-black text-gray-500 tracking-[0.2em] bg-transparent border-none focus:ring-1 focus:ring-blue-500 rounded"
                                  value={point.type}
                                  onChange={(e) => handleUpdatePoint(idx, { type: e.target.value as 'insight' | 'warning' | 'opportunity' | 'data' })}
                                >
                                  <option value="insight">INSIGHT</option>
                                  <option value="warning">WARNING</option>
                                  <option value="opportunity">OPPORTUNITY</option>
                                  <option value="data">DATA</option>
                                </select>
                                <span className="text-[9px] text-blue-400 font-bold">EDITABLE_ANALYSIS</span>
                              </div>
                            </div>
                        </Popup>
                      </CircleMarker>
                    ))}
                  </>
                )}
              </MapContainer>
            ) : (
              <div className="w-full h-full flex items-center justify-center p-4">
                <img 
                  src={res.imageUrl} 
                  alt="Spatial Analysis Result" 
                  className="max-w-full max-h-full object-contain rounded-xl shadow-2xl"
                  referrerPolicy="no-referrer"
                />
              </div>
            )}
            
            {/* Grid Overlay for Technical Feel */}
            {!isInteractive && (
              <div className="absolute inset-0 pointer-events-none opacity-[0.05]" 
                   style={{ backgroundImage: 'linear-gradient(#fff 1px, transparent 1px), linear-gradient(90deg, #fff 1px, transparent 1px)', backgroundSize: '40px 40px' }} />
            )}
          </div>
          
          <div className="px-8 py-6 bg-gray-900/50 border-t border-gray-800 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="flex flex-wrap items-center gap-6">
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-blue-500 shadow-[0_0_8px_rgba(59,130,246,0.5)]" />
                <span className="text-[10px] text-gray-400 font-bold uppercase tracking-wider">Strategic Node</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-green-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]" />
                <span className="text-[10px] text-gray-400 font-bold uppercase tracking-wider">Opportunity Area</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.5)]" />
                <span className="text-[10px] text-gray-400 font-bold uppercase tracking-wider">Critical Constraint</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-yellow-500 shadow-[0_0_8px_rgba(245,158,11,0.5)]" />
                <span className="text-[10px] text-gray-400 font-bold uppercase tracking-wider">Data Point</span>
              </div>
            </div>
            <div className="text-[10px] text-gray-500 font-bold tracking-widest uppercase flex items-center gap-4">
              <span>ENGINE: TANNMYAA_SPATIAL_V5</span>
              <span className="w-1 h-1 rounded-full bg-gray-700" />
              <span>DATUM: WGS 84</span>
              <span className="w-1 h-1 rounded-full bg-gray-700" />
              <span>PRECISION: ULTRA_HIGH</span>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );

  return (
    <GeneratorShell
      title="Spatial Analysis"
      description="Professional analytical urban maps grounded in real-world data and academic research."
      isLoading={isLoading || loading}
      error={error}
      result={result}
      renderInputForm={renderInputForm}
      renderResult={renderResult}
      userEmail={user?.email || null}
      onLogin={signInWithGoogle}
      onUpgrade={onUpgrade}
    />
  );
};

export default SpatialAnalysisGenerator;

